db:
  image: postgres:9.4.5
  volumes:
    - docker-flightsearch-postgres:/var/lib/postgresql/data

redis:
  image: redis
  ports:
    - '6379'  

sidekiq:
  build: .
  command: bundle exec sidekiq #-r app/workers/search_worker.rb #-L log/sidekiq.log
  links:
    - db
    - redis
  env_file: .env
  environment:
    RAILS_ENV: $RAILS_ENV

app:
  build: .
  env_file: .env
  environment:
    RAILS_ENV: $RAILS_ENV
  links:
    - db
    - redis
  ports:
   - "3000:3000" #"3000" #use "3000" if nginx is up


#web:
 
  # set the build context to the root of the Rails app
  #build: .
 
  # build with a different Dockerfile
  #dockerfile: config/containers/Dockerfile-nginx
  
  # makes the web container aware of the app container
  #links:
  #  - app
  
  # expose the port we configured Nginx to bind to
  #ports:
  # - "3000:80"