default: &default
  
  encoding: unicode
  pool: 25
  timeout: 5000
  

development:
  <<: *default
  host: db #localhost
  adapter: postgresql
  database: db/development
  port: 5432
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  host: db #localhost
  adapter: sqlite3
  database: db/test
  port: 5432
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %>

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %> 
  adapter: postgresql
  database: production
  port: 5432
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %> 

