 # SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#



default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000

development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: db/development
  pool: 25
  username: pguser
  password: myheart

test:
  <<: *default
  database: db/test
  username: sizief
  password: myheart

production:
  <<: *default
  database: db/production
  username: sizief
  password: myheart
