default: &default
  host: localhost
  encoding: unicode
  pool: 25
  timeout: 5000
  port: 5432
  username: <%= ENV["DB_USERNAME"] %> #postgres #
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  adapter: postgresql
  database: db/development

test:
  <<: *default
  adapter: sqlite3
  database: db/test

production:
  <<: *default
  adapter: postgresql
  database: db/production

