default: &default
  
  encoding: unicode
  pool: 25
  timeout: 5000
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  host: db #localhost
  adapter: postgresql
  database: db/development
  port: 5432

test:
  <<: *default
  host: db #localhost
  adapter: sqlite3
  database: db/test
  port: 5432

production:
  <<: *default
  host: postgresql://postgresql
  adapter: postgresql
  database: production
  port: 5432

