default: &default
  encoding: unicode
  pool: <%= ENV["DB_POOL"] %>
  timeout: 5000
  reaping_frequency: 1
  

development:
  <<: *default
  host: db #localhost 
  adapter: postgresql
  database: db/development
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USERNAME"] %> #<%= ENV["LOCAL_DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %> #<%= ENV["LOCAL_DB_PASSWORD"] %> #

test:
  <<: *default
  host: db #localhost
  adapter: sqlite3
  database: db/test
  port: 5432
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %>
  timeout: 5000

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %> 
  adapter: postgresql
  database: production
  port: <%= ENV["DB_PORT"] %> 
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %>