default: &default
  adapter: postgresql
  host: db #localhost
  encoding: unicode
  pool: 25
  timeout: 5000
  port: 5432
  username: postgres #<%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: db/development

test:
  <<: *default
  #adapter: sqlite3
  database: db/test

production:
  <<: *default
  database: db/production

