# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 212ff8c34422f7a0ac6bba79a5335c10d66c53fa260de4bd9c0373ebe85b2dea6289dac0ee0d68d35fa884a277197652295c24b0f2bd25046ade8ec3823d691b

test:
  secret_key_base: ae92e45924ede916294373542b75ea5a0870ec9978dbdfd0a2d2caf1c2d485fc6cd0c2a386560dd2a2e3817f87eeb9ec0fcefe1093e72ef40ee6ecfc9e17f743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
