#occupied: 
#every 00 or 20 or 40 ex: 15:00 or 15:30
#every 10 ex: 15:10
#all every hour and 50 minutes ex: 1:50
#1,2,7,7,13,15,19,21 and 30 min
:queues:
  - critical
  - default
  - low
:concurrency: 50
:schedule:
  today_flight_search: #every 20 minutes
    cron: '0 0,20,40 * * * *'
    args: [0]
    class: BackgroundSearchWorker

  tomorrow_flight_search: #every 60 minutes
    cron: '0 10 * * * *'
    args: [1]
    class: BackgroundSearchWorker

  dayafter_flight_search: #every 120 minutes
    cron: '0 50 0,2,4,6,8,10,12,14,16,18,20,22 * * *'
    args: [2]
    class: BackgroundSearchWorker

  restofweek_1_flight_search: #every 360 minutes
    cron: '0 50 1,7,13,19 * * *'
    args: [3]
    class: BackgroundSearchWorker

  restofweek_2_flight_search: #every 360 minutes
    cron: '0 50 3,9,15,21 * * *'
    args: [4]
    class: BackgroundSearchWorker

  restofweek_3_flight_search: #every 360 minutes
    cron: '0 50 5,11,17,23 * * *'
    args: [5]
    class: BackgroundSearchWorker

  restofweek_4_flight_search: #every 360 minutes
    cron: '0 30 1,7,13,19 * * *'
    args: [6]
    class: BackgroundSearchWorker

  restofweek_5_flight_search: #every 360 minutes
    cron: '0 30 3,9,15,21 * * *'
    args: [7]
    class: BackgroundSearchWorker

#airport search worker
  airport_data:
    cron: '0 0 0,12 * * *'
    class: AirportSearchWorker

#notification 
  price_alert:
    cron: '0 0 8 * * *'
    class: NotificationMailerWorker

#proxy
  proxy_update:
    cron: '0 /10 * * * *'
    class: ProxyUpdateWorker

  proxy_checker:
    cron: '0 /10 * * * *'
    class: ProxyCheckAllWorker

#flightPrice remover 
  flight_price_remover:
    cron: '0 /30 * * * *'
    class: FlightPriceRemoveWorker

#flightinfo worker 
  flight_info_worker:
    cron: '0 30 0,12 * * *'
    class: FlightInfoWorker