<% def interval(a) ([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41][a]*16).to_s+"m" end %>
:schedule:
  today_route_1:
    every: <%= interval(0) %>
    args: [<%= Date.today.to_s %>]
    class: SearchWorker

  tomorrow_route_1:
    every: <%= interval(2) %>
    args: [<%= (Date.today+1).to_s %>]
    class: SearchWorker

  dayafter_route_1:
    every: <%= interval(3) %>
    args: [<%= (Date.today+2).to_s %>]
    class: SearchWorker

  restofweek_1_route_1:
    every: <%= interval(4) %>
    args: [<%= (Date.today+3).to_s %>]
    class: SearchWorker

  restofweek_2_route_1:
    every: <%= interval(6) %>
    args: [<%= (Date.today+4).to_s %>]
    class: SearchWorker

  restofweek_3_route_1:
    every: <%= interval(8) %>
    args: [<%= (Date.today+5).to_s %>]
    class: SearchWorker

  restofweek_4_route_1:
    every: <%= interval(9) %>
    args: [<%= (Date.today+6).to_s %>]
    class: SearchWorker

  restofweek_5_route_1:
    every: <%= interval(10) %>
    args: [<%= (Date.today+7).to_s %>]
    class: SearchWorker

#airport search worker
  airports:
    every: "1440m"
    class: AirportSearchWorker

