#occupied: 
#every 00 or 30 ex: 15:00 or 15:30
#every 10 ex: 15:10
#all every hour and 50 minutes ex: 1:50
#1,2,7,7,13,15,19,21 and 20 min
:queues:
  - critical
  - default
  - low
:concurrency: 50
:schedule:
  today_route_1:
    cron: '0 0,30 * * * *'
    args: [<%= Date.today.to_s %>]
    class: BackgroundSearchWorker

  tomorrow_route_1:
    cron: '0 10 * * * *'
    args: [<%= (Date.today+1).to_s %>]
    class: BackgroundSearchWorker

  dayafter_route_1:
    cron: '0 50 0,2,4,6,8,10,12,14,16,18,20,22 * * *'
    args: [<%= (Date.today+2).to_s %>]
    class: BackgroundSearchWorker

  restofweek_1_route_1:
    cron: '0 50 1,7,13,19 * * *'
    args: [<%= (Date.today+3).to_s %>]
    class: BackgroundSearchWorker

  restofweek_2_route_1:
    cron: '0 50 3,9,15,21 * * *'
    args: [<%= (Date.today+4).to_s %>]
    class: BackgroundSearchWorker

  restofweek_3_route_1:
    cron: '0 50 5,11,17,23 * * *'
    args: [<%= (Date.today+5).to_s %>]
    class: BackgroundSearchWorker

  restofweek_4_route_1:
    cron: '0 20 1,7,13,19 * * *'
    args: [<%= (Date.today+6).to_s %>]
    class: BackgroundSearchWorker

  restofweek_5_route_1:
    cron: '0 20 3,9,15,21 * * *'
    args: [<%= (Date.today+7).to_s %>]
    class: BackgroundSearchWorker

#airport search worker
  airports:
    cron: '0 0 0,12 * * *'
    class: AirportSearchWorker

#notification 
  price_alert:
    cron: '0 0 8 * * *'
    class: NotificationMailerWorker

#proxy
  proxy_update:
    cron: '0 /10 * * * *'
    class: ProxyUpdateWorker

  proxy_checker:
    cron: '0 /10 * * * *'
    class: ProxyCheckAllWorker