#occupied: 
#every 00 or 20 or 40 ex: 15:00 or 15:30
#every 10 ex: 15:10
#all every hour and 50 minutes ex: 1:50
#1,2,7,7,13,15,19,21 and 30 min
<% if ENV["RAILS_ENV"] == "production" %>
:queues:
  - critical
  - default
  - low
:concurrency: 50
:schedule:
  flight_search_today: #every 10 minutes
    cron: '0 0,10,20,30,40,50 * * * *'
    args: [date_offset: 0]
    class: BackgroundSearchWorker

  flight_search_tomorrow: #every 20 minutes
    cron: '0 5,25,45 * * * *'
    args: [date_offset: 1]
    class: BackgroundSearchWorker

  flight_search_dayafter: #every 60 minutes
    cron: '0 15 * * * *'
    args: [date_offset: 2]
    class: BackgroundSearchWorker

  flight_search_restofweek_1: #every 120 minutes
    cron: '0 35 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
    args: [date_offset: 3]
    class: BackgroundSearchWorker

  flight_search_restofweek_2: #every 120 minutes
    cron: '0 55 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
    args: [date_offset: 4]
    class: BackgroundSearchWorker

  flight_search_restofweek_3: #every 120 minutes
    cron: '0 35 0,2,4,6,8,10,12,14,16,18,20,22 * * *'
    args: [date_offset: 5]
    class: BackgroundSearchWorker


#airport search worker
  get_airport_data:
    cron: '0 0 0,12 * * *'
    class: AirportSearchWorker

#notification 
#  price_alert:
#    cron: '0 0 8 * * *'
#    class: NotificationMailerWorker

#proxy
#  proxy_update:
#    cron: '0 /60 * * * *'
#    class: ProxyUpdateWorker

#  proxy_checker:
#    cron: '0 /61 * * * *'
#    class: ProxyCheckAllWorker

#flightPrice remover 
  flight_price_remover:
    cron: '0 /30 * * * *'
    class: FlightPriceRemoveWorker

#flightinfo worker 
  flight_info_worker:
    cron: '0 45 0,12 * * *'
    class: FlightInfoWorker

#route day worker
  route_day_worker:
    cron: '0 55 0,12 * * *'
    class: RouteDayWorker

#airline routes worker
  airline_rate_worker:
    cron: '0 /15 * * * *'
    class: AirlineRateWorker
<% end %>

#update most search routes
  update_most_search_routes:
    cron: '0 0 3 * * *'
    class: MostSearchRouteWorker

#daily background search
  daily_background_search:
    cron: '0 0 4 * * *'
    args: [type: "daily"]
    class: BackgroundSearchWorker