#occupied: 
#every 00 or 20 or 40 ex: 15:00 or 15:30
#every 10 ex: 15:10
#all every hour and 50 minutes ex: 1:50
#1,2,7,7,13,15,19,21 and 30 min
:queues:
  - critical
  - default
  - low
:concurrency: 50
:schedule:
  today_flight_search: #every 10 minutes
    cron: '0 0,10,20,30,40,50 * * * *'
    args: [0]
    class: BackgroundSearchWorker

  tomorrow_flight_search: #every 20 minutes
    cron: '0 5,25,45 * * * *'
    args: [1]
    class: BackgroundSearchWorker

  dayafter_flight_search: #every 60 minutes
    cron: '0 15 * * * *'
    args: [2]
    class: BackgroundSearchWorker

  restofweek_1_flight_search: #every 120 minutes
    cron: '0 35 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
    args: [3]
    class: BackgroundSearchWorker

  restofweek_2_flight_search: #every 120 minutes
    cron: '0 55 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
    args: [4]
    class: BackgroundSearchWorker

  restofweek_3_flight_search: #every 120 minutes
    cron: '0 35 0,2,4,6,8,10,12,14,16,18,20,22 * * *'
    args: [5]
    class: BackgroundSearchWorker

  restofweek_4_flight_search: #every 120 minutes
    cron: '0 55 0,2,4,6,8,10,12,14,16,18,20,22 * * *'
    args: [6]
    class: BackgroundSearchWorker

#airport search worker
  airport_data:
    cron: '0 0 0,12 * * *'
    class: AirportSearchWorker

#notification 
#  price_alert:
#    cron: '0 0 8 * * *'
#    class: NotificationMailerWorker

#proxy
#  proxy_update:
#    cron: '0 /60 * * * *'
#    class: ProxyUpdateWorker

#  proxy_checker:
#    cron: '0 /61 * * * *'
#    class: ProxyCheckAllWorker

#flightPrice remover 
  flight_price_remover:
    cron: '0 /30 * * * *'
    class: FlightPriceRemoveWorker

#flightinfo worker 
  flight_info_worker:
    cron: '0 45 0,12 * * *'
    class: FlightInfoWorker