#occupied: 
#every 00 or 20 or 40 ex: 15:00 or 15:30
#every 10 ex: 15:10
#all every hour and 50 minutes ex: 1:50
#1,2,7,7,13,15,19,21 and 30 min
<% if ENV["RAILS_ENV"] == "production" %>
:queues:
  - critical
  - default
  - low
:concurrency: 50
:schedule:
  flight_search_today: #every 10 minutes 720 times
    cron: '0 0,10,20,30,40,50 6-24 * * *'
    args: [date_offset: 0]
    class: BackgroundSearchWorker

  flight_search_tomorrow: #every 10 minutes 720 times
    cron: '0 5,15,25,35,45,55 6-24 * * *'
    args: [date_offset: 1]
    class: BackgroundSearchWorker

  flight_search_dayafter: #every 120 minutes 60
    cron: '0 55 0,6,8,10,12,14,16,18,20,22 * * *'
    args: [date_offset: 2]
    class: BackgroundSearchWorker

  flight_search_restofweek_1: #every 120 minutes 60
    cron: '0 35 1,7,9,11,13,15,17,19,21,23 * * *'
    args: [date_offset: 3]
    class: BackgroundSearchWorker

  flight_search_restofweek_2: #every 120 minutes 60
    cron: '0 55 1,7,9,11,13,15,17,19,21,23 * * *'
    args: [date_offset: 4]
    class: BackgroundSearchWorker

  flight_search_restofweek_3: #every 120 minutes 60
    cron: '0 35 0,6,8,10,12,14,16,18,20,22 * * *'
    args: [date_offset: 5]
    class: BackgroundSearchWorker


#airport search worker
  get_airport_data:
    cron: '0 0 0,12 * * *'
    class: AirportSearchWorker

#proxy
  proxy_update:
    cron: '0 /60 * * * *'
    class: ProxyUpdateWorker


#flightPrice remover 
  flight_price_remover:
    cron: '0 /30 * * * *'
    class: FlightPriceRemoveWorker

#flightinfo worker 
  flight_info_worker:
    cron: '0 45 0,12 * * *'
    class: FlightInfoWorker

#route day worker
  route_day_worker:
    cron: '0 55 0,12 * * *'
    class: RouteDayWorker

#airline routes worker
  review_rate_worker:
    cron: '0 /15 * * * *'
    class: ReviewRateWorker
<% end %>

#update most search routes
  update_most_search_routes:
    cron: '0 0 3 * * *'
    class: MostSearchRouteWorker

#daily background search
  daily_background_search:
    cron: '0 0 4 * * *'
    args: ["type": "daily"]
    class: BackgroundSearchWorker

#hourly monitoring 
  Monitor_Search:
    cron: '0 0 5,11,17,23 * * *'
    class: MonitorSearchWorker